services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./.config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
    - "host.docker.internal:host-gateway"